### PR TITLE
SC-93 tso500 vep

### PR DESCRIPTION
**Pull request by Addy81**
Restructured app to mirror what the vcf handler for uranus is doing with the addition of --exclude_null_alleles flag to exlcude multiple Cosmic IDs for the same variant, changes in the buffer size /form  and the addition of gnomad genomes as custom annotation.

All defaults annotation files suggested in the dxapp.json are for GRCh37.

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/2)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/2)* status: 0 of 3 files reviewed, 15 unresolved discussions (waiting on @Addy81 and @jethror1)

___
*[dxapp.json, line 68 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mpllmen752koCrYZ4S-:-Mpllmen752koCrYZ4S0:bru0cnq) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/dxapp.json#L68)):*
> ```JSON
>       "default": [
>         {
>           "$dnanexus_link": ""
> ```

why empty file id field?
___
*[dxapp.json, line 94 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MpllrQH8xN8v3LA1bTT:-MpllrQH8xN8v3LA1bTU:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/dxapp.json#L94)):*
> ```JSON
>       "class": "array:file",
>       "optional": false,
>       "default": [   
> ```

ws
___
*[dxapp.json, line 172 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmA6FEv2-gc1e5sOK:-MplmA6FEv2-gc1e5sOL:bi4xrti) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/dxapp.json#L172)):*
> ```JSON
>         "name": "htslib",
>         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>         "folder": "/app_assets/htslib/htslib_v1.14.0",
> ```

has this version finished being tested? Sophie was doing it but not sure if it was signed off to use
___
*[Readme.md, line 8 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmKPBAGgVXtM0zVFq:-MplmKPBAGgVXtM0zVFr:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L8)):*
> ```Markdown
> 
> ## What are typical use cases for this app?
> This app was designed to annotate vcfs with specified fields. 
> ```

ws
___
*[Readme.md, line 22 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmRZS0C5bagQ_c6Pp:-MplmRZS0C5bagQ_c6Pq:b7ugs2i) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L22)):*
> ```Markdown
> - dbSNP
> - ClinVar
> - ClinVar - Clinical Indication
> ```

Cosmic?
___
*[Readme.md, line 25 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmMX29XeeNROUFH1D:-MplmMX31Za33fPo5RUC:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L25)):*
> ```Markdown
> - ClinVar - Clinical Significance
> - Transcript Feature
>    
> ```

ws
___
*[Readme.md, line 45 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmcOr0ygUP6CddngI:-MplmcOr0ygUP6CddngJ:bwevqj3) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L45)):*
> ```Markdown
>       - CosmicNonCodingVariants_v94_grch37.normal.vcf.gz
>       - CosmicNonCodingVariants_v94_grch37.normal.vcf.gz.tbi
>   - ClinVar VCF (2021113)
> ```

date is missing a 1
___
*[Readme.md, line 54 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmiUzE8kV3mZ9PZuq:-MplmiUzE8kV3mZ9PZur:bz9t0v3) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L54)):*
> ```
> 
> ```
ws
___
*[Readme.md, line 65 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mplmve93wR0ss5ztvFh:-Mplmve93wR0ss5ztvFi:b-tueh24) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L65)):*
> ```Markdown
> ## Limitations
> - Designed to be used as part of Helios workflow for processing Solid Cancer data for GRCh37 so all defaults are based on that.
> - This app uses a buffer_size of 500 variants and parallelised using 4 cores. This was chosen with the solid cancer vcfs in mind and may need to be tweaked or changed for bigger vcfs.
> ```

have you tested with a larger vcf (whatever that might be) to see if it breaks or will just take longer?
___
*[Readme.md, line 66 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mpln0jN9sa4JSWNZJ-U:-Mpln0jN9sa4JSWNZJ-V:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L66)):*
> ```Markdown
> - Designed to be used as part of Helios workflow for processing Solid Cancer data for GRCh37 so all defaults are based on that.
> - This app uses a buffer_size of 500 variants and parallelised using 4 cores. This was chosen with the solid cancer vcfs in mind and may need to be tweaked or changed for bigger vcfs.
>   
> ```

ws
___
*[src/code.sh, line 40 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplnDHp5H1-FS4jHwCM:-MplnDHp5H1-FS4jHwCN:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L40)):*
> ```Shell
>   	gnomad_genome_vcf=$(find ./ -name "gnomad.genomes.*.vcf.gz" | sed s'/.\///')
> 
> 	# --exclude_null_allelels is used with --check-existing to prevent multiple COSMIC id's 
> ```

ws
___
*[src/code.sh, line 70 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplnT401fhdjJar7NbZ:-MplnT401fhdjJar7Nb_:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L70)):*
> ```Shell
> 	find ~/in/vep_annotation -type f -name "*" -print0 | xargs -0 -I {} mv {} ~/in/vep_annotation
> 
> 	# move annotation sources and input vcf to home 
> ```

ws
___
*[src/code.sh, line 84 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mplnl4g3Y-RUtMFf8v9:-Mplnl4g3Y-RUtMFf8vA:b2kgk8g) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L84)):*
> ```Shell
> 	# place fasta and indexes for VEP in the annotation folder
> 	chmod a+rwx /home/dnanexus/in/vep_refs/*fa.gz*
> 	mv /home/dnanexus/in/vep_refs/*fa.gz* ~/homo_sapiens_refseq/104_GRCh37/
> ```

can this be not hard coded? its an input so an update to a new version would then require a change to the code because of this instead of just config
___
*[src/code.sh, line 103 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MploFig9vZ7J8x_5ctb:-MploFig9vZ7J8x_5ctc:b5hsy14) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L103)):*
> ```Shell
>   # upload output files
> 
> 	# Upload output vcf
> ```

I think you have a mix of tabs and spaces, below is 4 spaces and everything above seems to be double tabbed
___
*[src/code.sh, line 107 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplodBJ6W65U-l50zUJ:-MplodBJ6W65U-l50zUK:b-cubown) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L107)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     # The following line(s) use the utility dx-jobutil-add-output to format and
>     # add output variables to your job's output as appropriate for the output
>     # class.  Run "dx-jobutil-add-output -h" for more information on what it
>     # does.
> 
> ```
</details>

delete

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/2)* status: 0 of 3 files reviewed, 15 unresolved discussions (waiting on @jethror1)

___
*[dxapp.json, line 68 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mpllmen752koCrYZ4S-:-MppZH620QdJodbbWb1V:b-p2h7rb) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/dxapp.json#L68)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why empty file id field?
</blockquote></details>

it disappeared, now solved.
___
*[dxapp.json, line 94 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MpllrQH8xN8v3LA1bTT:-MppZKK8CQ28HCTDMKJF:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/dxapp.json#L94)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.
___
*[dxapp.json, line 172 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmA6FEv2-gc1e5sOK:-MppZLjn8FEPPz7uxYGf:b8ec0xh) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/dxapp.json#L172)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

has this version finished being tested? Sophie was doing it but not sure if it was signed off to use
</blockquote></details>

I'll check with Sophie
___
*[Readme.md, line 8 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmKPBAGgVXtM0zVFq:-MppZPaK0QInJx5NqiKf:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L8)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.
___
*[Readme.md, line 22 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmRZS0C5bagQ_c6Pp:-MppZV__1Ixt5iBcGVmZ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L22)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Cosmic?
</blockquote></details>

Done.
___
*[Readme.md, line 25 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmMX29XeeNROUFH1D:-MppZVyVCAbccViSyUzn:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L25)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.
___
*[Readme.md, line 45 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmcOr0ygUP6CddngI:-MppZhbb8GIjuEkBKg0s:b-xntghr) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L45)):*
> ```
> done
> ```
___
*[Readme.md, line 54 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmiUzE8kV3mZ9PZuq:-MppZpaFDa77FjA57jbu:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L54)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

> ```
> 
> ```
ws
</blockquote></details>

Done.
___
*[Readme.md, line 65 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mplmve93wR0ss5ztvFh:-MppZrIcE6QJfslBZfAH:b-980sem) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L65)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

have you tested with a larger vcf (whatever that might be) to see if it breaks or will just take longer?
</blockquote></details>

planning to find one now.
___
*[Readme.md, line 66 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mpln0jN9sa4JSWNZJ-U:-MppZueG6jKUL9L-TjtH:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L66)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.
___
*[src/code.sh, line 40 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplnDHp5H1-FS4jHwCM:-MppZv-g8uPnkoYsmtkR:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L40)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.
___
*[src/code.sh, line 70 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplnT401fhdjJar7NbZ:-MppZvfECD-08GWupSxo:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L70)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.
___
*[src/code.sh, line 84 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mplnl4g3Y-RUtMFf8v9:-MppZw01D_Rg5ZC_8TYH:b-uw8mxx) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L84)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can this be not hard coded? its an input so an update to a new version would then require a change to the code because of this instead of just config
</blockquote></details>

I can try, but it is what the *tar.gz unpacks to so it can be unpredictable if you change the annotation  Equally it wouldn't work for 38 in this case. I'll have a think.
___
*[src/code.sh, line 103 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MploFig9vZ7J8x_5ctb:-MppaCol5w1fYEGjD5nz:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L103)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I think you have a mix of tabs and spaces, below is 4 spaces and everything above seems to be double tabbed
</blockquote></details>

Done.
___
*[src/code.sh, line 107 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplodBJ6W65U-l50zUJ:-MppaDd25-FXl4m2kO_u:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L107)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

> ```
>     # The following line(s) use the utility dx-jobutil-add-output to format and
>     # add output variables to your job's output as appropriate for the output
>     # class.  Run "dx-jobutil-add-output -h" for more information on what it
>     # does.
> 
> ```
delete
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/2)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jethror1)

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/2)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Addy81 and @jethror1)

___
*[src/code.sh, line 84 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mplnl4g3Y-RUtMFf8v9:-Mpq5T6EDKruobiTxVtC:bnfz1gg) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L84)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

I can try, but it is what the *tar.gz unpacks to so it can be unpredictable if you change the annotation  Equally it wouldn't work for 38 in this case. I'll have a think.
</blockquote></details>

something like this should work if there's only one sub dir:
```
$ mkdir -p parent_test/child_test
$ find parent_test -mindepth 1 -maxdepth 1 -type d
parent_test/child_test
```

If you do have more than one (and know part of the name i.e. grch3[7/8]
```
$ mkdir parent_test/bad_child

$ ls parent_test/
bad_child  child_test

$ find parent_test -mindepth 1 -maxdepth 1 -type d -name "*test*"
parent_test/child_test
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/2)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Addy81 and @jethror1)

___
*[Readme.md, line 65 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mplmve93wR0ss5ztvFh:-Mpv4-4I0hJVZ2FjG9Fs:b-mt9la7) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L65)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

planning to find one now.
</blockquote></details>

if you want to make the number of cores used for vep the maximum available (not sure why you wouldn't) you can get it from `/proc/cpuinfo`:

```
$ grep -c ^processor /proc/cpuinfo
8
```
This will return the number of threads (i.e. on Intel CPUs it will be 4 cores -> 8 threads), not sure what workstations have but you might want half of that instead, or just make this and the buffer optional inputs I guess

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/2)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[dxapp.json, line 172 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-MplmA6FEv2-gc1e5sOK:-MqKlq9w4ePdMhWGGNzr:bxdw02u) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/dxapp.json#L172)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

I'll check with Sophie
</blockquote></details>

After discussion with Wook he suggested not to change it and use this as evidence it works.
___
*[Readme.md, line 65 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mplmve93wR0ss5ztvFh:-MqPrB-y4JKXzlrKTITn:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L65)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

if you want to make the number of cores used for vep the maximum available (not sure why you wouldn't) you can get it from `/proc/cpuinfo`:

```
$ grep -c ^processor /proc/cpuinfo
8
```
This will return the number of threads (i.e. on Intel CPUs it will be 4 cores -> 8 threads), not sure what workstations have but you might want half of that instead, or just make this and the buffer optional inputs I guess
</blockquote></details>

Done.
___
*[src/code.sh, line 84 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mplnl4g3Y-RUtMFf8v9:-MqPrBss1APDa_9ZOBHM:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/src/code.sh#L84)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

something like this should work if there's only one sub dir:
```
$ mkdir -p parent_test/child_test
$ find parent_test -mindepth 1 -maxdepth 1 -type d
parent_test/child_test
```

If you do have more than one (and know part of the name i.e. grch3[7/8]
```
$ mkdir parent_test/bad_child

$ ls parent_test/
bad_child  child_test

$ find parent_test -mindepth 1 -maxdepth 1 -type d -name "*test*"
parent_test/child_test
```
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/2)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Addy81 and @jethror1)

___
*[Readme.md, line 65 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-Mplmve93wR0ss5ztvFh:-MqPtPCG4y9sNeHWDXmg:bf02cm9) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/d56bc69b627b6e68a49c81552a513fa5bd2b3c86/Readme.md#L65)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

need to change the readme to say it uses the total number of cores provided, no longer hardcoded to 4

**Review by jethror1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/2)* status: all files reviewed, 1 unresolved discussion (waiting on @Addy81)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-:-MqPx0WM-bN_-JSC1QDE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Addy81)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/2#-:-MqPx2Ld3qXJ3OmPurTS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Addy81)

**Pull request merged**
