### PR TITLE
allow additional flags

### PR DESCRIPTION
**Pull request by kjwinfield**
This update to eggd_vep will allow additional flags to be passed in through an `additional_flags` field in the eggd_vep config file. A `_format_additional_flags` function has been added to extract additional flags from the config file and add these flags to the created string for the VEP command.

Relates to this Git Issue [https://github.com/eastgenomics/eggd_vep/issues/16](https://github.com/eastgenomics/eggd_vep/issues/16)

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/20)

### CODE REVIEW

**Review by Addy81 — CHANGES_REQUESTED** [review]
Can we update the READMe to mention if additional flags are needed to be added to both the available sections in the config?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/20#-:-NS6pkPs9H9oP2I1ov6d:b-s49cr5)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`src/code.sh` line 154 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/20#-NS6otqPBkC9a2YW6oal:-NS6otqPBkC9a2YW6oam:b-qzx6in) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/39f499fa0ca66927fd71fac58742c295bcd7352e/src/code.sh#L154)):*
> ```Shell
> 
> 	for flag in $(jq -c '.additional_flags[]' "$file")
> 	do 	flag="${flag%\"}"
> ```

Could the do and flag be in separate lines to meet the indentation of the rest of the script?

**Review by Addy81 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/20)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`src/code.sh` line 154 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/20#-NS6otqPBkC9a2YW6oal:-NS6rugK1b_jSXVyFZJD:bde1ozb) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/39f499fa0ca66927fd71fac58742c295bcd7352e/src/code.sh#L154)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Could the do and flag be in separate lines to meet the indentation of the rest of the script?
</blockquote></details>

You can also pass jq -r option and it will automatically remove the "" around the results. So you can do 



_Code snippet:_
```Shell
for flag in $(jq -r -c '.additional_flags[]' "$file")
do
	ADDITIONAL_FLAGS+="--$flag ";
done
```

**Review by kjwinfield — COMMENTED** [review]
New DNAnexus job with additional flags [here](https://platform.dnanexus.com/projects/GQK5vjQ40949KB275K3YxxyJ/monitor/job/GQbxJK840945Vvk3zpX96BbP)

New DNAnexus job with no additional flags [here](https://platform.dnanexus.com/projects/GQK5vjQ40949KB275K3YxxyJ/monitor/job/GQbxK3Q40948PG1xpZ6FZ7BP)

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/20#-:-NSASub504Pko96vPeRq:b-n8y26b)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Addy81)

___
*[`src/code.sh` line 154 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep/20#-NS6otqPBkC9a2YW6oal:-NSAQt_W3--1pxGRHHdl:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/39f499fa0ca66927fd71fac58742c295bcd7352e/src/code.sh#L154)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

You can also pass jq -r option and it will automatically remove the "" around the results. So you can do 
</blockquote></details>

Done.

**Review by Addy81 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kjwinfield)

**Comment by mattgarner** [comment]
Not merged since changes were included in another branch (DI-174_v1.3.0)

**Pull request closed without merging**
