### PR TITLE
Changes for compatibility with CNV annotation

### LINKED ISSUE #12: Space before the end of the line
At the Docker command make sure there's a whitespace before the line break so the command strings do not get merged.
[line 38 and 39](https://github.com/eastgenomics/eggd_vep/blob/main/src/code.sh#L38)

### PR DESCRIPTION
**Pull request by Addy81**
This resolves #12 and #13 to accomodate CNVs.

Main change is the addition of the optional flag  `toNormalise` which is set to true as default but not compatible with CNV calling.
Minor changes to edit comments and correct typos also included.

Example jobs:
* this works for CNVs: https://platform.dnanexus.com/projects/G8x02384xVp3Qvj73P3ZxKjK/monitor/job/GFBgPY84xVp6pXPq3ZgV6493 
* this works for CNVs + filtering: https://platform.dnanexus.com/projects/G8x02384xVp3Qvj73P3ZxKjK/monitor/job/GFBk15j4xVp7JpgkG96ZY827
* this still works for SNVs and normalisation works as expected: https://platform.dnanexus.com/projects/G8x02384xVp3Qvj73P3ZxKjK/monitor/job/GFBjYj84xVp3pV9G6Xq8Fxg2

```
# diff of output of original job and output of rerun using same inputs with new app version
diff <(dx cat project-GF62QG045V8k6qX5F5gXXJV7:file-GF7xZ0841V0zQg3BKJJY0j4q| zcat) <(dx cat project-G8x02384xVp3Qvj73P3ZxKjK:file-GFBjqv049F6jg3139Fp3V3b8|zcat)
118,119c118,119
< ##bcftools_normCommand=norm -f genome.fa -m -any --keep-sum AD -o X221668-GM1915714-1-CEN-F-EGG5_markdup_recalibrated_Haplotyper_normalised.vcf -; Date=Thu Jul 14 08:52:55 2022
< ##VEP="v105" time="2022-07-14 08:55:19" cache="/opt/vep/.vep/homo_sapiens_refseq/105_GRCh37" ensembl=105.f357e33 ensembl-io=105.2a0a40c ensembl-variation=105.ac8178e ensembl-funcgen=105.660df8f 1000genomes="phase3" COSMIC="92" ClinVar="202012" HGMD-PUBLIC="20204" assembly="GRCh37.p13" dbSNP="154" gencode="GENCODE 19" genebuild="2011-04" gnomAD="r2.1" polyphen="2.2.2" refseq="2020-10-26 17:03:42 - GCF_000001405.25_GRCh37.p13_genomic.gff" regbuild="1.0" sift="sift5.2.2"
---
> ##bcftools_normCommand=norm -f genome.fa -m -any --keep-sum AD -o X221668-GM1915714-1-CEN-F-EGG5_markdup_recalibrated_Haplotyper_post_filtering.vcf X221668-GM1915714-1-CEN-F-EGG5_markdup_recalibrated_Haplotyper_filtered.vcf; Date=Mon Jul 18 16:42:11 2022
> ##VEP="v105" time="2022-07-18 16:44:24" cache="/opt/vep/.vep/homo_sapiens_refseq/105_GRCh37" ensembl=105.f357e33 ensembl-variation=105.ac8178e ensembl-io=105.2a0a40c ensembl-funcgen=105.660df8f 1000genomes="phase3" COSMIC="92" ClinVar="202012" HGMD-PUBLIC="20204" assembly="GRCh37.p13" dbSNP="154" gencode="GENCODE 19" genebuild="2011-04" gnomAD="r2.1" polyphen="2.2.2" refseq="2020-10-26 17:03:42 - GCF_000001405.25_GRCh37.p13_genomic.gff" regbuild="1.0" sift="sift5.2.2"
```

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/17)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/17)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Addy81 and @mattgarner)

___
*[`dxapp.json` line 52 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vep/17#-N7HI8EHArToX3pkPWbl:-N7HI8EHArToX3pkPWbm:b-vhu95) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/dd03065e957f2775d68a38c3dc9da6a28a9c4897/dxapp.json#L52)):*
> ```JSON
>     },
>     {
>       "name": "toNormalise",
> ```

can we stick to snake case for the name, its confusing having arguments with a mix of snake case and camel case
___
*[`dxapp.json` line 126 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vep/17#-N7HKJrkEzTo2O_oYvUu:-N7HKJrkEzTo2O_oYvUv:bj027a6) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/dd03065e957f2775d68a38c3dc9da6a28a9c4897/dxapp.json#L126)):*
> ```JSON
>     ],
>     "contactEmail": "East GLH Bioinformatics",
>     "whatsNew": "* 1.0.0 First release of VEP app with modular annotation inputs.\n"
> ```

needs updating if this field is being kept
___
*[`Readme.md` line 82 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vep/17#-N7HIQDs-NR_hfuWVdbW:-N7HIQDs-NR_hfuWVdbX:brqb87m) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/dd03065e957f2775d68a38c3dc9da6a28a9c4897/Readme.md#L82)):*
> ```Markdown
> - A panel bed file to filter the vcf on (`panel_bed`)
> - A list of transcripts to filter on (`transcript_list`). One transcript per line. VEP annotates with all possible transcripts and if this list is passed it filters on the given transcript list.
> ```

normalisation argument to add here
___
*[`src/code.sh` line 220 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vep/17#-N7HJHh76ks0_nhah0kE:-N7HJHh76ks0_nhah0kF:bo67oja) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/dd03065e957f2775d68a38c3dc9da6a28a9c4897/src/code.sh#L220)):*
> ```Shell
> 	else
> 		echo "No filtering was applied"
> 		cp "${vcf_path}" "${vcf_prefix}_filtered.vcf"
> ```

why `cp` over `mv`? using `cp ` will require creating a new file which for big VCFs would take an amount of time, `mv` is pretty much instant

also don't like that is is called `_filtered` when it isn't actually filtered. Is this just a tmp file in the app and not uploaded? Could be confusing if its output

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/17)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`dxapp.json` line 52 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vep/17#-N7HI8EHArToX3pkPWbl:-N7HvBnZ9Dzq_Slb28WT:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/dd03065e957f2775d68a38c3dc9da6a28a9c4897/dxapp.json#L52)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can we stick to snake case for the name, its confusing having arguments with a mix of snake case and camel case
</blockquote></details>

Done.
___
*[`dxapp.json` line 126 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vep/17#-N7HKJrkEzTo2O_oYvUu:-N7Hw5fr4kA7M-7n0UYi:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/dd03065e957f2775d68a38c3dc9da6a28a9c4897/dxapp.json#L126)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

needs updating if this field is being kept
</blockquote></details>

Done.
___
*[`Readme.md` line 82 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vep/17#-N7HIQDs-NR_hfuWVdbW:-N7Hxi3P5PQSMXJGjRZq:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/dd03065e957f2775d68a38c3dc9da6a28a9c4897/Readme.md#L82)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

normalisation argument to add here
</blockquote></details>

Done.
___
*[`src/code.sh` line 220 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vep/17#-N7HJHh76ks0_nhah0kE:-N7Hyg_rB28dcwxriyy8:b-k365i3) ([raw file](https://github.com/eastgenomics/eggd_vep/blob/dd03065e957f2775d68a38c3dc9da6a28a9c4897/src/code.sh#L220)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why `cp` over `mv`? using `cp ` will require creating a new file which for big VCFs would take an amount of time, `mv` is pretty much instant

also don't like that is is called `_filtered` when it isn't actually filtered. Is this just a tmp file in the app and not uploaded? Could be confusing if its output
</blockquote></details>

Changed cp to move but will leave the filtered the same and deal with in the next version.

**Review by Addy81 — COMMENTED** [review]
Rerun with pr changes: https://platform.dnanexus.com/projects/G8x02384xVp3Qvj73P3ZxKjK/monitor/job/GFBv50j4xVp0b60kJ04813xY

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/17#-:-N7I16cN3OVDvsLHrQv3:brfdptu)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @mattgarner)

**Review by jethror1 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Pull request merged**
